{% set name = "emsdk" %}
{% set version = "3.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/emscripten-core/emsdk/archive/{{ version }}.tar.gz
  sha256: 3a207eed627366d9a7b31a634fa97c365cea0b6564b27e0cfadf7e53781606a3

build:
  skip: true  # [win]
  number: 1

requirements:
  run:
    - python
    - nodejs

test:
  commands:
    - emsdk help
    - emsdk install 3.1.2
    - emsdk activate 3.1.2

about:
  home: https://github.com/emscripten-core/emsdk
  summary: Emscripten SDK
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/emscripten-core/emsdk

extra:
  recipe-maintainers:
    - martinRenou
